[包]
格式 = 2
名称 = "yanxu-macos-ui"
版本 = "0.7.1"
言序 = ">=1.1.7"
入口 = "src/言序麦金塔界面.yx"
说明 = "言序的麦金塔原生 SwiftUI/AppKit 界面与体验描述库"
许可 = "MIT"
作者 = ["言序团队"]

[依赖]

[权限]
文件 = []
网络 = []
TCP监听 = []
UDP绑定 = []
环境 = []
进程 = false
原生扩展 = false

[导出]
默认 = "src/言序麦金塔界面.yx"

[原生]
ABI = 2

[原生.macos.aarch64]
文件 = "native/aarch64-apple-darwin/libYanxuMacUIHost.dylib"
校验和 = "2cb7cb13b791a0dd21ce6992a8186e27c23a9052a98de5a806a95bc1b4d6247b"
大小 = 1111832

[资源]
目录 = ["native/aarch64-apple-darwin"]

[构建]
目标 = "字节码"
